// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxbfhissilssquyotlrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4YmZoaXNzaWxzc3F1eW90bHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMzU1MTQsImV4cCI6MjA1MTYxMTUxNH0.OzLvIaQ12HBYXkFHeXLbNm3Xt7hiL3NWuXyC4jQPHaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);